[package]
name = "Rust"
version = "0.1.0"
authors = ["zeus <zeusperezgarcia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
insta = { version = "1.34.0", features = ["ron"] }
